# Generated by Django 6.0.3 on 2026-04-06 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ig_handle', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('valid_till', models.DateTimeField(blank=True, help_text='Approving root user sets this to +365 days', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('semester', models.PositiveSmallIntegerField(help_text='Standardized school term: 1, 2, or 3')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g. 2025/2026', max_length=9)),
                ('designation', models.CharField(max_length=100)),
                ('is_root', models.BooleanField(default=False, help_text='Only the root user can assign other admins')),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='committee_members', to='feed.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Committee',
            },
        ),
        migrations.AddField(
            model_name='club',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='feed.institution'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Expired', 'Expired')], default='Active', max_length=20)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='feed.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PastEventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drive_file_id', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(max_length=500)),
                ('is_public', models.BooleanField(default=False, help_text='If false, only club members can view')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='feed.event')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ig_id', models.CharField(max_length=255, unique=True)),
                ('short_code', models.CharField(max_length=50)),
                ('caption', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('Announcement', 'Announcement'), ('Recruitment', 'Recruitment'), ('Workshop', 'Workshop')], max_length=50, null=True)),
                ('type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Reel', 'Reel')], max_length=20)),
                ('timestamp', models.DateTimeField(help_text='The original Instagram post creation time')),
                ('is_edited', models.BooleanField(default=False, help_text='Set to true if admin manually overrides scraped data')),
                ('is_public', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='feed.club')),
            ],
        ),
        migrations.CreateModel(
            name='LinkClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('label', models.CharField(help_text='e.g., Registration Form', max_length=255)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='feed.post')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='feed.post'),
        ),
    ]
