# Generated by Django 6.0.3 on 2026-05-12 01:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_claimed', models.BooleanField(default=False)),
                ('membership_fee', models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0 if the club is free to join.', max_digits=6)),
                ('payment_qr_code', models.ImageField(blank=True, help_text='Upload your DuitNow or TNG QR code.', null=True, upload_to='club_qrs/')),
                ('ig_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('valid_till', models.DateTimeField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club_logos/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='club_banners/')),
                ('payment_qr', models.ImageField(blank=True, null=True, upload_to='club_payment_qrs/')),
                ('social_instagram', models.URLField(blank=True, max_length=500, null=True)),
                ('social_linkedin', models.URLField(blank=True, max_length=500, null=True)),
                ('social_facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('social_twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('social_website', models.URLField(blank=True, max_length=500, null=True)),
                ('social_discord', models.URLField(blank=True, max_length=500, null=True)),
                ('last_fetched_date', models.DateTimeField(blank=True, null=True)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('renewal_policy', models.CharField(choices=[('ROLLING', '1 Year from Join Date'), ('CALENDAR', 'Ends December 31st Every Year'), ('LIFETIME', 'Pay Once, Never Renew')], default='ROLLING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Club Categories',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='institutions/')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='states/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('student_name', models.CharField(max_length=255)),
                ('student_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('bio', models.TextField(blank=True, null=True)),
                ('alternative_email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('faculty', models.CharField(blank=True, choices=[('FCI', 'Faculty of Computing and Informatics'), ('FOM', 'Faculty of Management'), ('FAIE', 'Faculty of Artificial Intelligence and Engineering'), ('FCM', 'Faculty of Creative Multimedia'), ('FAC', 'Faculty of Applied Communication'), ('FCA', 'Faculty of Cinematic Arts'), ('FOL', 'Faculty of Law'), ('FIST', 'Faculty of Information Science and Technology'), ('FOB', 'Faculty of Business')], max_length=50, null=True)),
                ('major', models.CharField(blank=True, max_length=100, null=True)),
                ('year_of_study', models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('YEAR 1', 'Degree - Year 1'), ('YEAR 2', 'Degree - Year 2'), ('YEAR 3', 'Degree - Year 3'), ('YEAR 4', 'Degree - Year 4'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='customuser_auth_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='customuser_auth_permissions', to='auth.permission', verbose_name='user permissions')),
                ('joined_clubs', models.ManyToManyField(blank=True, related_name='members_joined', to='core.club')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proof_document', models.FileField(upload_to='claim_proofs/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('claimer_designation', models.CharField(default='President', max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='club_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='core.clubcategory'),
        ),
        migrations.CreateModel(
            name='ClubScrapeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('phase', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_item', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('current_image', models.PositiveIntegerField(default=0)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('failed_items', models.JSONField(blank=True, default=list, help_text='List of items that failed to process (e.g. image downloads)', null=True)),
                ('club', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_status', to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('event_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PREPARING', 'Preparing'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='PREPARING', max_length=15)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.club')),
            ],
        ),
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_image', models.ImageField(upload_to='certificate_templates/')),
                ('name_center_x', models.IntegerField()),
                ('name_center_y', models.IntegerField()),
                ('font_size', models.IntegerField(default=24)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('font_name', models.CharField(choices=[('Helvetica-Bold', 'Helvetica Bold'), ('Helvetica', 'Helvetica Regular'), ('Times-Bold', 'Times Bold'), ('Times-Roman', 'Times Regular'), ('Courier-Bold', 'Courier Bold'), ('Courier', 'Courier Regular')], default='Helvetica-Bold', max_length=50)),
                ('custom_text', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_x', models.IntegerField(blank=True, null=True)),
                ('custom_y', models.IntegerField(blank=True, null=True)),
                ('custom_font_size', models.IntegerField(default=20)),
                ('custom_font_color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.event')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='core.institution'),
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('UNLIMITED', 'Unlimited (Paid)'), ('LIMITED', 'Limited (Interest)')], default='LIMITED', max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(max_length=100)),
                ('caption', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('INDUSTRIAL_VISIT', 'Industrial Visit'), ('ANNOUNCEMENT', 'Announcement'), ('PAST_EVENT', 'Past Event'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('local_image', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('ig_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.club')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.post'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/')),
                ('order', models.PositiveIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.post')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PreRegisteredAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_ready', models.BooleanField(default=False)),
                ('is_attended', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registered', to='core.event')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='institution',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.state'),
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_emails', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClubManager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ROOT', 'Root Admin'), ('NON_ROOT', 'Non-Root Admin')], max_length=15)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='core.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_clubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'ROOT')), fields=('club',), name='unique_root_per_club')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guest_name', models.CharField(blank=True, max_length=255, null=True)),
                ('guest_email', models.EmailField(blank=True, max_length=255, null=True)),
                ('guest_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('certificate_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.event')),
            ],
            options={
                'unique_together': {('event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['ig_handle'], name='core_club_ig_hand_9b921f_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['last_fetched_date'], name='core_club_last_fe_bea10d_idx'),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_club_name_per_institution'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['club', '-timestamp'], name='core_post_club_id_4d4fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-timestamp'], name='core_post_timesta_0d7300_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='core_event_event_d_ed494e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preregisteredattendee',
            unique_together={('event', 'user')},
        ),
    ]
