# Generated by Django 5.2.13 on 2026-05-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='Membership_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0 if the club is free to join.', max_digits=6),
        ),
        migrations.AddField(
            model_name='club',
            name='payment_qr_code',
            field=models.ImageField(blank=True, help_text='Upload your DuitNow or TNG QR code.', null=True, upload_to='club_qrs/'),
        ),
    ]
