# Generated by Django 6.0.3 on 2026-05-02 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='membership_type',
        ),
    ]
