# Generated by Django 6.0.3 on 2026-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='last_fetched_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['ig_handle'], name='core_club_ig_hand_9b921f_idx'),
        ),
        migrations.AddIndex(
            model_name='club',
            index=models.Index(fields=['last_fetched_date'], name='core_club_last_fe_bea10d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_date'], name='core_event_event_d_ed494e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['club', '-timestamp'], name='core_post_club_id_4d4fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-timestamp'], name='core_post_timesta_0d7300_idx'),
        ),
    ]
