# Generated by Django 6.0.4 on 2026-05-13 09:47

import core.models_taskrebased
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='check_in_time',
            new_name='scanned_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[core.models_taskrebased.validate_mmu_email]),
        ),
    ]
