# Generated by Django 6.0.3 on 2026-04-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='ig_hanlde',
        ),
        migrations.AddField(
            model_name='club',
            name='ig_handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clubclaim',
            name='claimer_designation',
            field=models.CharField(default='Member', max_length=100),
        ),
    ]
