# Generated by Django 6.0.3 on 2026-05-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_membership_membership_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='font_name',
            field=models.CharField(choices=[('Helvetica-Bold', 'Helvetica Bold'), ('Helvetica', 'Helvetica Regular'), ('Times-Bold', 'Times Bold'), ('Times-Roman', 'Times Regular'), ('Courier-Bold', 'Courier Bold'), ('Courier', 'Courier Regular')], default='Helvetica-Bold', max_length=50),
        ),
    ]
