# Generated by Django 6.0.3 on 2026-04-08 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_club_ig_hanlde_club_ig_handle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_image', models.ImageField(upload_to='certificate_templates/')),
                ('name_center_x', models.IntegerField()),
                ('name_center_y', models.IntegerField()),
                ('font_size', models.IntegerField(default=24)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_type', models.CharField(choices=[('UNLIMITED', 'Unlimited (Paid)'), ('LIMITED', 'Limited (Interest)')], max_length=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='payment_proofs/')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreRegisteredAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='certificatetemplate',
            name='club',
        ),
        migrations.RemoveConstraint(
            model_name='committee',
            name='unique_root_per_club',
        ),
        migrations.AddField(
            model_name='attendance',
            name='certificate_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='guest_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='local_image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/ig/'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.event'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='clubclaim',
            name='claimer_designation',
            field=models.CharField(default='Club Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='core.event'),
        ),
        migrations.AddField(
            model_name='membership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.club'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_registered', to='core.event'),
        ),
        migrations.DeleteModel(
            name='CertificateTemplate',
        ),
        migrations.AlterUniqueTogether(
            name='preregisteredattendee',
            unique_together={('event', 'email')},
        ),
    ]
