# Generated by Django 5.2.13 on 2026-05-03 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_club_membership_fee_club_payment_qr_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='Membership_fee',
            new_name='membership_fee',
        ),
    ]
