# Generated by Django 6.0.3 on 2026-04-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_club_alter_event_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregisteredattendee',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
