# Generated by Django 6.0.4 on 2026-05-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_check_in_time_attendance_scanned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_event',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
