# Generated by Django 6.0.4 on 2026-04-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='user',
            name='alt_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
