# Generated by Django 5.2.13 on 2026-05-03 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_membership_fee_club_membership_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='alt_email',
            new_name='alternative_email',
        ),
    ]
