# Generated by Django 6.0.4 on 2026-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_post_is_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('INDUSTRIAL_VISIT', 'Industrial Visit'), ('ANNOUNCEMENT', 'Announcement')], default='MISC', max_length=20),
        ),
    ]
