# Generated by Django 6.0.3 on 2026-04-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_preregisteredattendee_is_attended_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
