# Generated by Django 6.0.3 on 2026-04-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_post_image_url_remove_post_local_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ig_id',
        ),
    ]
