# Generated by Django 6.0.3 on 2026-04-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_event_is_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
