# Generated by Django 6.0.3 on 2026-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_post_ig_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/'),
        ),
    ]
