# Generated by Django 6.0.4 on 2026-05-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_bio_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('FCI', 'Faculty of Computing and Informatics'), ('FOM', 'Faculty of Management'), ('FAIE', 'Faculty of Artificial Intelligence and Engineering'), ('FCM', 'Faculty of Creative Multimedia'), ('FAC', 'Faculty of Applied Communication'), ('FCA', 'Faculty of Cinematic Arts'), ('FOL', 'Faculty of Law'), ('FIST', 'Faculty of Information Science and Technology'), ('FOB', 'Faculty of Business')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
    ]
