# Generated by Django 6.0.4 on 2026-05-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_faculty_user_major_user_year_of_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('YEAR 1', 'Degree - Year 1'), ('YEAR 2', 'Degree - Year 2'), ('YEAR 3', 'Degree - Year 3'), ('YEAR 4', 'Degree - Year 4'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
    ]
