# Generated by Django 6.0.3 on 2026-04-21 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_club_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preregisteredattendee',
            old_name='name',
            new_name='guest_name',
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='preregisteredattendee',
            unique_together={('event', 'user')},
        ),
        migrations.AddField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.club'),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='guest_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('event', 'user')},
        ),
        migrations.RemoveField(
            model_name='preregisteredattendee',
            name='email',
        ),
    ]
