# Generated by Django 6.0.3 on 2026-04-27 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_event_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='revenue',
        ),
    ]
