# Generated by Django 6.0.3 on 2026-04-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_event_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='PREPARING', max_length=15),
        ),
    ]
