# Generated by Django 6.0.4 on 2026-05-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_year_of_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='joined_clubs',
            field=models.ManyToManyField(blank=True, related_name='members_joined', to='core.club'),
        ),
    ]
