# Generated by Django 6.0.3 on 2026-04-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_preregisteredattendee_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('PAST_EVENT', 'Past Event'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='is_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clubclaim',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
