# Generated by Django 6.0.4 on 2026-05-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('PAST_EVENT', 'Past Event'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
        ),
    ]
