# Generated by Django 6.0.4 on 2026-05-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_useremail'),
        ('core', '0009_remove_club_category_post_category'),
    ]

    operations = [
    ]
