# Generated by Django 6.0.4 on 2026-05-05 06:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20260504_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubclaim',
            name='club',
        ),
        migrations.RemoveField(
            model_name='clubclaim',
            name='user',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='club',
        ),
        migrations.RemoveField(
            model_name='committee',
            name='user',
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='claimer_designation',
            field=models.CharField(default='President', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='club_banners/'),
        ),
        migrations.AddField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('PAST_EVENT', 'Past Event'), ('MISC', 'Miscellaneous')], default='MISC', max_length=20),
        ),
        migrations.AddField(
            model_name='club',
            name='payment_qr',
            field=models.ImageField(blank=True, null=True, upload_to='club_payment_qrs/'),
        ),
        migrations.AddField(
            model_name='club',
            name='social_discord',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='social_facebook',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='social_instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='social_linkedin',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='social_twitter',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='social_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='clubmanager',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clubmanager',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('UNLIMITED', 'Unlimited (Paid)'), ('LIMITED', 'Limited (Interest)')], default='LIMITED', max_length=15),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('FCI', 'Faculty of Computing and Informatics'), ('FOM', 'Faculty of Management'), ('FAIE', 'Faculty of Artificial Intelligence and Engineering'), ('FCM', 'Faculty of Creative Multimedia'), ('FAC', 'Faculty of Applied Communication'), ('FCA', 'Faculty of Cinematic Arts'), ('FOL', 'Faculty of Law'), ('FIST', 'Faculty of Information Science and Technology'), ('FOB', 'Faculty of Business')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='joined_clubs',
            field=models.ManyToManyField(blank=True, related_name='members_joined', to='core.club'),
        ),
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='user',
            name='year_of_study',
            field=models.CharField(blank=True, choices=[('Foundation', 'Foundation'), ('Diploma', 'Diploma'), ('YEAR 1', 'Degree - Year 1'), ('YEAR 2', 'Degree - Year 2'), ('YEAR 3', 'Degree - Year 3'), ('YEAR 4', 'Degree - Year 4'), ('Masters', 'Masters'), ('PhD', 'PhD')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club_logos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='clubmanager',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='clubmanager',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'ROOT')), fields=('club',), name='unique_root_per_club'),
        ),
        migrations.DeleteModel(
            name='ClubClaim',
        ),
        migrations.DeleteModel(
            name='Committee',
        ),
    ]
