# Generated by Django 6.0.4 on 2026-05-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_clubclaim_club_remove_clubclaim_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubScrapeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_task_name', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('phase', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('current_item', models.PositiveIntegerField(default=0)),
                ('total_items', models.PositiveIntegerField(default=0)),
                ('current_image', models.PositiveIntegerField(default=0)),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('extra', models.JSONField(blank=True, null=True)),
                ('club', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='scrape_status', to='core.club')),
            ],
        ),
    ]
