# Generated by Django 6.0.4 on 2026-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_clubclaim_club_remove_clubclaim_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_club_name_per_institution'),
        ),
    ]
