# Generated by Django 6.0.4 on 2026-05-08 00:00

from django.db import migrations, models
import uuid


def populate_clubmanager_new_id(apps, schema_editor):
    ClubManager = apps.get_model('core', 'ClubManager')
    for manager in ClubManager.objects.all():
        manager.new_id = uuid.uuid5(uuid.NAMESPACE_URL, f'clubmanager-{manager.id}')
        manager.save(update_fields=['new_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_club_scrape_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmanager',
            name='new_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.RunPython(populate_clubmanager_new_id, migrations.RunPython.noop),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    """
                    ALTER TABLE core_clubmanager DROP CONSTRAINT core_clubmanager_pkey;
                    ALTER TABLE core_clubmanager RENAME COLUMN id TO old_id;
                    ALTER TABLE core_clubmanager RENAME COLUMN new_id TO id;
                    ALTER TABLE core_clubmanager ADD PRIMARY KEY (id);
                    ALTER TABLE core_clubmanager DROP COLUMN old_id;
                    """,
                    None,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='clubmanager',
                    name='id',
                    field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                migrations.RemoveField(
                    model_name='clubmanager',
                    name='new_id',
                ),
            ],
        ),
    ]
