# Generated by Django 6.0.3 on 2026-05-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_club_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='scanned_at',
            new_name='check_in_time',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('PREPARING', 'Preparing'), ('ONGOING', 'Ongoing'), ('FINISHED', 'Finished')], default='PREPARING', max_length=15),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='font_name',
            field=models.CharField(choices=[('Helvetica-Bold', 'Helvetica Bold'), ('Helvetica', 'Helvetica Regular'), ('Times-Bold', 'Times Bold'), ('Times-Roman', 'Times Regular'), ('Courier-Bold', 'Courier Bold'), ('Courier', 'Courier Regular')], default='Helvetica-Bold', max_length=50),
        ),
    ]
