# Generated by Django 6.0.4 on 2026-05-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_convert_clubmanager_to_uuid'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('institution', 'name'), name='unique_club_name_per_institution'),
        ),
    ]
