# Generated by Django 6.0.3 on 2026-05-07 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_eventcertificate_font_name'),
        ('core', '0013_rename_scanned_at_attendance_check_in_time_and_more'),
    ]

    operations = [
    ]
