# Generated by Django 6.0.5 on 2026-05-11 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_scanned_at_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Club Categories',
            },
        ),
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_y',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='club_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='core.clubcategory'),
        ),
    ]
