# Generated by Django 5.2.14 on 2026-05-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_scanned_at_attendance_check_in_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='renew_policy',
            field=models.CharField(choices=[('ROLLING', '1 Year from Join Date'), ('CALENDAR', 'Ends December 31st Every Year'), ('LIFETIME', 'Pay Once, Never Renew')], default='ROLLING', max_length=20),
        ),
        migrations.AddField(
            model_name='membership',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
