# Generated by Django 5.2.14 on 2026-05-10 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_club_renew_policy_membership_expired_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='renew_policy',
            new_name='renewal_policy',
        ),
    ]
