# Generated by Django 6.0.4 on 2026-05-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_club_unique_club_name_per_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubscrapestatus',
            name='failed_items',
            field=models.JSONField(blank=True, default=list, help_text='List of items that failed to process (e.g. image downloads)', null=True),
        ),
    ]
