# Generated by Django 6.0.5 on 2026-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20260507_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('UNLIMITED', 'Unlimited (Paid)'), ('LIMITED', 'Limited (Interest)')], default='LIMITED', max_length=15),
        ),
    ]
