# Generated by Django 6.0.5 on 2026-05-10 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_membership_membership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Club Categories',
            },
        ),
        migrations.RemoveField(
            model_name='club',
            name='category',
        ),
        migrations.AddField(
            model_name='club',
            name='club_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clubs', to='core.clubcategory'),
        ),
    ]
