# Generated by Django 6.0.5 on 2026-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clubcategory_remove_club_category_club_club_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_font_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_font_size',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_text',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_x',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventcertificate',
            name='custom_y',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
