# Generated by Django 6.0.5 on 2026-05-17 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_post_category'),
        ('core', '0017_eventcertificate_custom_font_color_and_more'),
    ]

    operations = [
    ]
