# Generated by Django 6.0.5 on 2026-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_merge_20260518_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='club_category',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Academic & Professional'), (1, 'Sports & Recreation'), (2, 'Arts & Culture'), (3, 'Community Service'), (4, 'Technology & Innovation'), (5, 'Special Interest'), (6, 'Other')], default=6, null=True),
        ),
        migrations.DeleteModel(
            name='ClubCategory',
        ),
    ]
