# Generated by Django 6.0.6 on 2026-06-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum number of attendees. Leave blank for unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Set to 0 if the event is free.', max_digits=6),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, help_text='When registration closes.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='If true, host must manually approve attendees.'),
        ),
    ]
