# Generated by Django 6.0.6 on 2026-06-05 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_event_end_time_event_start_time_event_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qr_token',
            field=models.CharField(blank=True, help_text='Current active token for QR check-in', max_length=64, null=True),
        ),
    ]
