# Generated by Django 6.0.4 on 2026-06-05 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_event_end_time_event_start_time_event_timezone'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='clubmanager',
            name='unique_root_per_club',
        ),
    ]
