# Generated by Django 6.0.4 on 2026-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_remove_clubmanager_unique_root_per_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='extracted_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
