# Generated by Django 6.0.6 on 2026-06-08 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_event_qr_token'),
        ('core', '0025_post_extracted_details'),
    ]

    operations = [
    ]
