# Generated by Django 6.0.6 on 2026-06-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_merge_0024_event_qr_token_0025_post_extracted_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='join_mode',
            field=models.CharField(choices=[('FREE', 'Free to Join'), ('REQUEST', 'Request to Join (Approval required)'), ('RSVP', 'External RSVP Link'), ('FEE', 'Pay to Join (Requires receipt)')], default='FREE', max_length=15),
        ),
        migrations.AddField(
            model_name='event',
            name='rsvp_link',
            field=models.URLField(blank=True, help_text='Link for external RSVP', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='event_receipts/'),
        ),
        migrations.AddField(
            model_name='preregisteredattendee',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='extracted_details',
            field=models.JSONField(blank=True, default=dict, help_text='Parsed event metadata such as date, venue, and registration link.', null=True),
        ),
    ]
