# Generated by Django 6.0.6 on 2026-06-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_event_join_mode_event_rsvp_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_qr',
            field=models.ImageField(blank=True, help_text='Payment QR code for this event', null=True, upload_to='event_payment_qrs/'),
        ),
    ]
