# Generated by Django 6.0.6 on 2026-06-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_event_payment_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='encrypted_apify_api_key',
            field=models.TextField(blank=True, null=True),
        ),
    ]
