# Generated by Django 6.0.6 on 2026-06-14 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_club_encrypted_apify_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='core.event'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['event'], name='core_post_event_i_f7a539_idx'),
        ),
    ]
