# Generated by Django 6.0.6 on 2026-06-14 16:20

from django.db import migrations


def copy_post_to_event(apps, schema_editor):
    Event = apps.get_model('core', 'Event')
    Post = apps.get_model('core', 'Post')
    for event in Event.objects.all():
        if getattr(event, 'post_id', None):
            try:
                post = Post.objects.get(id=event.post_id)
                post.event_id = event.id
                post.save()
            except Post.DoesNotExist:
                pass

def reverse_copy(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_post_event_post_core_post_event_i_f7a539_idx'),
    ]

    operations = [
        migrations.RunPython(copy_post_to_event, reverse_copy),
    ]
