# Generated by Django 6.0.6 on 2026-06-14 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20260615_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='post',
        ),
    ]
