# Generated by Django 6.0.6 on 2026-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_event_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_primary_event_post',
            field=models.BooleanField(default=False),
        ),
    ]
