# Generated by Django 6.0.6 on 2026-06-19 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_post_is_primary_event_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name': 'Club Join Request', 'verbose_name_plural': 'Club Join Requests'},
        ),
    ]
