# Generated by Django 6.0.6 on 2026-06-19 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_membership_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={},
        ),
    ]
