# Generated by Django 6.0.6 on 2026-06-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_membership_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RECRUITMENT', 'Recruitment'), ('COMPETITION', 'Competition'), ('WORKSHOP', 'Workshop'), ('INDUSTRIAL_VISIT', 'Industrial Visit')], default='MISC', max_length=20),
        ),
    ]
