# Generated by Django 5.2.14 on 2026-06-29 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClubRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
                ('category', models.PositiveSmallIntegerField(choices=[(0, 'Academic & Professional'), (1, 'Sports & Recreation'), (2, 'Arts & Culture'), (3, 'Community Service'), (4, 'Technology & Innovation'), (5, 'Special Interest'), (6, 'Other')], default=6)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.institution')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
